<?php
$REXVALUE = array();
$REXVALUE[1] = 'REX_VALUE[1]';
$REXVALUE[2] = 'REX_VALUE[2]';
$REXVALUE[3] = 'REX_VALUE[3]';
$REXVALUE[4] = 'REX_VALUE[4]';
$REXVALUE[5] = 'REX_VALUE[5]';
$REXVALUE[6] = 'REX_VALUE[6]';
$REXVALUE[7] = 'REX_VALUE[7]';
$REXVALUE[8] = 'REX_VALUE[8]';
$REXVALUE[9] = 'REX_VALUE[9]';
$REXVALUE[10] = 'REX_VALUE[10]';
$REXVALUE[11] = 'REX_VALUE[11]';
$REXVALUE[12] = 'REX_VALUE[12]';
$REXVALUE[13] = 'REX_VALUE[13]';
$REXVALUE[14] = 'REX_VALUE[14]';

include_once($REX["INCLUDE_PATH"].'/addons/qp_coverflow/output/frontend.inc.php');
include($REX["INCLUDE_PATH"].'/addons/qp_coverflow/output/frontend.inc.php');
?>
