<style type="text/css">
.qp{}
.qp h2{
	font-size: 1.2em;
	padding-bottom: 6px;
	margin-bottom: 9px;
	border-bottom: 1px solid #aaa;
}
.qp p.descrP{
	padding-bottom: 24px;
}

.qp dl {
	clear: both;
	margin: 0 0 12px;
	padding: 6px 0;
	border-bottom: 1px solid #ddd;
}
.qp dl dt {
	float: left;
	text-align: right;
	width: 100px;
	font-weight: bold;
}
/*.qp dl dt::after {
	content: ':';
}*/
.qp dl dd {
	margin-left: 120px;
}
.qp dl dd .descr {
	padding: 6px 0 0;
	font-size: 1em;
}
.qp dl dd .descr small{
	font-size: 0.95em;
}
.qp dl dd .descr small.list{
	display: block;
	margin: 6px 0;
	padding: 9px;
	border: 1px solid #ddd;
}
</style>

<div class="qp">

	<?php
	include_once($REX['INCLUDE_PATH'].'/addons/qp_coverflow/functions/qp_coverflow-module.inc.php');

	$timestamp = microtime_string();

	$REXVALUE = array();

	// REX_VALUE muss als String übergeben werden,
	// da es Platzhalter sind, die anschliessend
	// ersetzt werden.
	$REXVALUE[1] = 'REX_VALUE[1]';
	$REXVALUE[1] = (isset($REXVALUE[1]) && $REXVALUE[1]!="")? $REXVALUE[1] : $timestamp;
	// jQueryUI-Checkbox
	$REXVALUE[9] = 'REX_VALUE[9]';
	$REXVALUE[9] = (isset($REXVALUE[9]) && $REXVALUE[9]!="")? "checked=\"checked\"" : "";
	// jQuery-Checkbox
	$REXVALUE[10] = 'REX_VALUE[10]';
	$REXVALUE[10] = (isset($REXVALUE[10]) && $REXVALUE[10]!="")? "checked=\"checked\"" : "";

	echo('  <h2>qpCoverflow - Konfiguration</h2>');
	echo('  <p class="descrP">Im nachstehenden Formular kann das Coverflow-Addon konfiguriert werden.<br />Für nicht gesetzte Optionen werden deren Default-Werte genommen.</p>');
	// echo('  <div>qpCoverflow-ID: coverflow_' . $REXVALUE[1] . '</div>');
	// echo('  <input type="hidden" class="text" name="VALUE[1]" value="' . $REXVALUE[1] . '">');

	echo('	<dl>');
	echo('		<dt>Coverflow-ID</dt>');
	echo('		<dd>');
	echo('			coverflow_' . $REXVALUE[1] . '<input type="hidden" class="text" name="VALUE[1]" value="' . $REXVALUE[1] . '">');
	echo('		</dd>');
	echo('	</dl>');

	?>
	<dl>
		<dt>Bilder</dt>
		<dd>
			<div>
				Bilder für Coverflow auswählen.
			</div>
			<div>REX_MEDIALIST_BUTTON[1]</div>
		</dd>
	</dl>
	<dl>
		<dt>Breite</dt>
		<dd>
			<div><input type="text" class="text" name="VALUE[2]" value="REX_VALUE[2]"></div>
			<div class="descr">
				(integer, string) - Breite des Coverflows (z.B. 400, 90%, auto)<br />
				Default: auto
			</div>
		</dd>
	</dl>
	<dl>
		<dt>Höhe</dt>
		<dd>
			<div><input type="text" class="text" name="VALUE[3]" value="REX_VALUE[3]"></div>
			<div class="descr">
				(integer) - Höhe des Coverflows<br />
				Default: 300
			</div>
		</dd>
	</dl>
	<dl>
		<dt>Start</dt>
		<dd>
			<div><input type="text" class="text" name="VALUE[4]" value="REX_VALUE[4]"></div>
			<div class="descr">
				(integer, string) - Index des Bildes, das zuerst in der Mitte angezeigt werden soll (auto = Bild in der Mitte des Arrays)<br />
				Default: auto
			</div>
		</dd>
	</dl>
	<dl>
		<dt>items</dt>
		<dd>
			<div><input type="text" class="text" name="VALUE[5]" value="REX_VALUE[5]"></div>
			<div class="descr">
				(integer) - Anzahl ungekippter Bilder<br />
				Default: 3
			</div>
		</dd>
	</dl>
	<dl>
		<dt>Margin</dt>
		<dd>
			<div><input type="text" class="text" name="VALUE[6]" value="REX_VALUE[6]"></div>
			<div class="descr">
				(integer) - Abstand zwischen den Bildern (von 0 .. 20)<br />
				Default: 5
			</div>
		</dd>
	</dl>
	<dl>
		<dt>Kipp-Winkel</dt>
		<dd>
			<div><input type="text" class="text" name="VALUE[7]" value="REX_VALUE[7]"></div>
			<div class="descr">
				(integer) - Kipp-Winkel von 0 .. 75 Grad<br />
				Default: 60
			</div>
		</dd>
	</dl>
	<dl>
		<dt>Schrittweite</dt>
		<dd>
			<div><input type="text" class="text" name="VALUE[8]" value="REX_VALUE[8]"></div>
			<div class="descr">
				(integer) - Schrittweite beim Kippen der Bilder (von 1 .. 20)<br /> <small>(Je kleiner der Wert, desto genauer die Darstellung, aber umso rechenaufwändiger)</small><br />
				Default: 5
			</div>
		</dd>
	</dl>
	<dl>
		<dt>jQuery</dt>
		<dd>
			<div><input name="VALUE[10]" type="checkbox" id="VALUE[10]" value="1" <?php echo($REXVALUE[10]); ?> /></div>
			<div class="descr">
				(boolean) - Das jQuery-Framework ist notwendig, dass das Coverflow-AddOn funktioniert. Wird im Frontend gar nichts angezeigt, muss der Haken für diese Option gesetzt werden.<br /><small class="list">- Sollten <b>mehr</b> Coverflows auf einer Seite eingebunden sein, reicht es, den Haken bei <b>einem Block</b> zu setzen.<br />- Fehlen jQuery und jQueryUI, so müssen die Haken für <b>beide</b> Frameworks im <b>gleichen</b> Block gesezt werden.</small><br />
				Default: nicht gesetzt
			</div>
		</dd>
	</dl>
	<dl>
		<dt>jQueryUI</dt>
		<dd>
			<div><input name="VALUE[9]" type="checkbox" id="VALUE[9]" value="1" <?php echo($REXVALUE[9]); ?> /></div>
			<div class="descr">
				(boolean) - Das jQueryUI-Framework ist notwendig, dass das Coverflow-AddOn funktioniert. Wird im Frontend nur ein Bild statt des Coverflows angezeigt, fehlt das jQueryUI-Framework und der Haken für diese Option muss gesetzt werden.<br /><small class="list">- Sollten <b>mehr</b> Coverflows auf einer Seite eingebunden sein, reicht es, den Haken bei <b>einem Block</b> zu setzen.<br />- Fehlen jQuery und jQueryUI, so müssen die Haken für <b>beide</b> Frameworks im <b>gleichen</b> Block gesezt werden.</small><br />
				Default: nicht gesetzt
			</div>
		</dd>
	</dl>
</div>
