<?php
include_once($REX['INCLUDE_PATH'].'/addons/qp_coverflow/functions/qp_coverflow-module.inc.php');

$timestamp = microtime_string();

$REXVALUE = array();
$REXVALUE[1] = 'REX_VALUE[1]';

$REXVALUE[1] = (isset($REXVALUE[1]) && $REXVALUE[1]!="")? $REXVALUE[1] : $timestamp;

echo('<h3>qpCoverflow-ID: coverflow_' . $REXVALUE[1] . '</h3>');
echo('<input type="hidden" class="text" name="VALUE[1]" value="' . $REXVALUE[1] . '">');
?>
